apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: elasticsearch2
  namespace: elastic
spec:
  version: 9.1.0
  remoteClusters:
    - name: elasticsearch1
      elasticsearchRef:
        name: elasticsearch1
  nodeSets:
  - name: default
    count: 1
    config:
      node.store.allow_mmap: false
    podTemplate:
      spec:
        containers:
        - name: elasticsearch
          resources:
            requests:
              memory: 2Gi
              cpu: 1
            limits:
              memory: 2Gi
              cpu: 1
  http:
    service:
      spec:
        type: NodePort
        ports:
        - name: https
          port: 9200
          targetPort: 9200
          nodePort: 30201