apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:
  name: kibana2
  namespace: elastic
spec:
  version: 9.1.0
  count: 1
  elasticsearchRef:
    name: elasticsearch2
  http:
    service:
      spec:
        type: NodePort
        ports:
        - port: 5601
          targetPort: 5601
          nodePort: 30602